# Generated by Django 6.0.3 on 2026-03-30 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('online', 'Онлайн-касса'), ('transfer', 'Переводом'), ('cash', 'Наличными')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('indoor', 'Крытая'), ('outdoor', 'Уличная')], default='outdoor', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('payment_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_competitions', to=settings.AUTH_USER_MODEL)),
                ('payment_methods', models.ManyToManyField(blank=True, to='competitions.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=100)),
                ('sport_class', models.CharField(max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('judge_name', models.CharField(blank=True, max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('competition', 'discipline', 'sport_class')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('waiting_owner', 'Ожидает подтверждения владельца')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Чек на проверке'), ('paid', 'Оплачено')], default='unpaid', max_length=20)),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='competitions.competition')),
                ('entries', models.ManyToManyField(related_name='applications', to='competitions.entry')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='competitions.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('sort_value', models.FloatField(default=0)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.application')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.entry')),
            ],
            options={
                'unique_together': {('application', 'entry')},
            },
        ),
    ]
