# Generated by Django 6.0.3 on 2026-03-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_entry_sport_class'),
        ('users', '0002_alter_dog_sport_class_alter_userprofile_sport_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Зачёт', 'verbose_name_plural': 'Зачёты'},
        ),
        migrations.AlterModelOptions(
            name='organizercontact',
            options={'verbose_name': 'Контакт организатора', 'verbose_name_plural': 'Контакты организаторов'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Способ оплаты', 'verbose_name_plural': 'Способы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='application',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='application',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.dog', verbose_name='Собака'),
        ),
        migrations.AlterField(
            model_name='application',
            name='entries',
            field=models.ManyToManyField(related_name='applications', to='competitions.entry', verbose_name='Выбранные зачёты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='Чек об оплате'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Не оплачено'), ('pending', 'Чек на проверке'), ('paid', 'Оплачено')], default='unpaid', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('waiting_owner', 'Ожидает подтверждения владельца')], default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Спортсмен'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location_type',
            field=models.CharField(choices=[('indoor', 'Крытая'), ('outdoor', 'Уличная')], default='outdoor', max_length=10, verbose_name='Тип площадки'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_competitions', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срок оплаты'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, to='competitions.paymentmethod', verbose_name='Способы оплаты'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='registration_deadline',
            field=models.DateField(verbose_name='Дата закрытия записи'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='discipline',
            field=models.CharField(max_length=100, verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Взнос'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judged_entries', to=settings.AUTH_USER_MODEL, verbose_name='Судья (зарегистрированный)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='judge_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Судья (вручную)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='sport_class',
            field=models.CharField(choices=[('novice', 'Новички'), ('progress', 'Прогресс'), ('open', 'Открытый')], default='novice', max_length=20, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='organizercontact',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='competitions.competition', verbose_name='Соревнование'),
        ),
        migrations.AlterField(
            model_name='organizercontact',
            name='contact_type',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('vk', 'ВКонтакте'), ('telegram', 'Telegram')], max_length=20, verbose_name='Тип контакта'),
        ),
        migrations.AlterField(
            model_name='organizercontact',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='code',
            field=models.CharField(choices=[('online', 'Онлайн-касса'), ('transfer', 'Переводом'), ('cash', 'Наличными')], max_length=20, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='result',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.application', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='result',
            name='data',
            field=models.JSONField(default=dict, verbose_name='Данные результата'),
        ),
        migrations.AlterField(
            model_name='result',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.entry', verbose_name='Зачёт'),
        ),
        migrations.AlterField(
            model_name='result',
            name='place',
            field=models.IntegerField(blank=True, null=True, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='result',
            name='sort_value',
            field=models.FloatField(default=0, verbose_name='Значение для сортировки'),
        ),
    ]
