# Generated by Django 6.0.3 on 2026-03-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_application_options_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('file', models.FileField(upload_to='competition_files/%Y/%m/%d/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='competitions.competition', verbose_name='Соревнование')),
            ],
            options={
                'verbose_name': 'Файл соревнования',
                'verbose_name_plural': 'Файлы соревнований',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
