# Generated by Django 6.0.3 on 2026-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competitionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='discipline',
            field=models.CharField(choices=[('bullseye', 'Буллсай'), ('distance', 'Броски на дальность'), ('accuracy', 'Броски на точность')], max_length=20, verbose_name='Дисциплина'),
        ),
    ]
