# Generated by Django 6.0.3 on 2026-03-30 13:09

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_entry_judge_alter_result_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='entries',
        ),
        migrations.CreateModel(
            name='ApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_entries', to='competitions.application', verbose_name='Заявка')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_entries', to='competitions.entry', verbose_name='Зачёт')),
            ],
            options={
                'verbose_name': 'Заявка-Зачёт',
                'verbose_name_plural': 'Выбранные зачёты в заявках',
                'unique_together': {('application', 'entry')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='result',
            name='application_entry',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='application', chained_model_field='application', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.applicationentry', verbose_name='Заявка и зачёт'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('application', 'application_entry')},
        ),
        migrations.RemoveField(
            model_name='result',
            name='entry',
        ),
    ]
