# Generated by Django 6.0.3 on 2026-04-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_result_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='organizer_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий организатора'),
        ),
    ]
