# Generated by Django 6.0.3 on 2026-04-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_alter_result_unique_together_alter_result_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
