# Generated by Django 6.0.3 on 2026-04-07 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_competition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='judge',
        ),
        migrations.CreateModel(
            name='EntryJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_judges', to='competitions.entry', verbose_name='Зачёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_entries', to=settings.AUTH_USER_MODEL, verbose_name='Судья')),
            ],
            options={
                'verbose_name': 'Назначение судьи',
                'verbose_name_plural': 'Назначения судей',
                'unique_together': {('entry', 'user')},
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='judging_entries_m2m', through='competitions.EntryJudge', to=settings.AUTH_USER_MODEL, verbose_name='Судьи (зарегистрированные)'),
        ),
    ]
