# Generated by Django 6.0.3 on 2026-04-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_remove_entry_judge_entryjudge_entry_judges'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
    ]
