# Generated by Django 6.0.3 on 2026-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0016_competition_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена'), ('waiting_owner', 'Ожидает подтверждения владельца'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
