# Generated by Django 6.0.3 on 2026-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='can_enter_without_class',
            field=models.BooleanField(default=False, help_text='Если включено, участники могут выступать вне конкурсной программы', verbose_name='Можно вне зачёта'),
        ),
    ]
