# Generated by Django 6.0.3 on 2026-04-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_entry_can_enter_without_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationentry',
            name='is_out_of_class',
            field=models.BooleanField(default=False, verbose_name='Вне зачёта'),
        ),
    ]
