# Generated by Django 6.0.3 on 2026-05-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0019_applicationentry_is_out_of_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время проведения'),
        ),
    ]
