# Generated by Django 6.0.3 on 2026-03-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='sport_class',
            field=models.CharField(choices=[('novice', 'Новички'), ('progress', 'Прогресс'), ('open', 'Открытый')], default='novice', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sport_class',
            field=models.CharField(choices=[('novice', 'Новички'), ('progress', 'Прогресс'), ('open', 'Открытый')], default='novice', max_length=20),
        ),
    ]
