# Generated by Django 6.0.3 on 2026-03-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_dog_sport_class_alter_userprofile_sport_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dog',
            options={'verbose_name': 'Собака', 'verbose_name_plural': 'Собаки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterField(
            model_name='dog',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/dogs', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(blank=True, max_length=100, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='sport_class',
            field=models.CharField(choices=[('novice', 'Новички'), ('progress', 'Прогресс'), ('open', 'Открытый')], default='novice', max_length=20, verbose_name='Класс собаки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/users', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sport_class',
            field=models.CharField(choices=[('novice', 'Новички'), ('progress', 'Прогресс'), ('open', 'Открытый')], default='novice', max_length=20, verbose_name='Класс спортсмена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
