# Generated by Django 6.0.3 on 2026-04-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_dog_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Кобель'), ('female', 'Сука')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
