# Generated by Django 6.0.3 on 2026-04-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dog_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organizer_requested',
            field=models.BooleanField(default=False, verbose_name='Запросил роль организатора'),
        ),
    ]
