# Generated by Django 6.0.3 on 2026-04-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_is_organizer_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('app_status', 'Изменение статуса заявки'), ('app_payment', 'Статус оплаты заявки'), ('app_new', 'Новая заявка на вашу собаку'), ('comp_reminder', 'Напоминание о соревновании'), ('result_ready', 'Результаты опубликованы'), ('system', 'Системное уведомление')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка (URL)')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'), models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx')],
            },
        ),
    ]
