# Generated by Django 6.0.3 on 2026-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('guide', 'Гайд'), ('athletes', 'Спортсменам'), ('organizers', 'Организаторам'), ('rules', 'Правила'), ('training', 'Тренировки')], default='other', max_length=20, verbose_name='Тег'),
        ),
    ]
